# Generated by Django 4.1.7 on 2023-09-01 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0002_remove_clientes_informacoes_usuario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidos',
            name='codigo_rastreio',
            field=models.CharField(default=0, max_length=10),
        ),
        migrations.AlterField(
            model_name='pedidos',
            name='status_pedido',
            field=models.CharField(choices=[('T', 'Entregue'), ('A', 'Transporte')], default='A', max_length=1),
        ),
    ]
